# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
logging:
  level:
    root: DEBUG

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/REPLACE_WITH_YOUR_NAME_DATABASE
    username: REPLACE_WITH_YOUR_USERNAME_DATABASE
    password: REPLACE_WITH_YOUR_PASSWORD_DATABASE
    hikari:
      poolName: Hikari
      auto-commit: false
      minimum-idle: 10
      maximum-pool-size: 50
  liquibase:
    contexts: dev
#  mail:
#    host: REPLACE_WITH_YOUR_HOST_SMTP
#    port: REPLACE_WITH_YOUR_PORT_SMTP
#    username: REPLACE_WITH_YOUR_USERNAME_SMTP
#    password: REPLACE_WITH_YOUR_PASSWORD_SMTP
#    protocol: smtp
#    tls: true
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls.enable: true

server:
  8080